### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by himynameisdave** [rowanmanning/list-all-files#92]
It would be great to have a CLI version of this package! My use case is that I am not using this in a project/wouldn't need to install it to a local `package.json`, and am instead using it as a one-off.

My ideal use case is something like this:

```bash
npx @rowanmanning/list-all-files someDirectory/
```

Similarly a CLI for this package could be installed globally with NPM.

It doesn't even need to be a part of this package/project, it could be broken off into a separate `@rowanmanning/list-all-files-cli` which then just uses this package (similar to how `sindresorhus` separates them, for example the [`rgb-hex-cli`](https://www.npmjs.com/package/rgb-hex-cli) which uses the [`rgb-hex`](https://www.npmjs.com/package/rgb-hex) lib under the hood).

**Comment by rowanmanning** [comment]
Hi @himynameisdave 👋 thanks for the feedback but I'm not going to add or build a CLI for this as it sits outside my needs. Feel free to release something yourself, but I'd normally fall back on built-in command line tools for something like this. E.g. this probably does what you'd be looking for (at least on a Unix-based machine):

```sh
find . -type f
```
